### ISSUE TITLE
Hiding on activity list only

### ISSUE THREAD

**Issue by ZiadJ** [arjunsuresh/qa-filtertags#1]
Is it possible to hide the questions from the questions and activity list only? I'm planning to add quiz questions as well that use the poll plugin to record the answers and I would tag them with keywords like 'quiz' but I don't want them to show up in any question list.

**Comment by arjunsuresh** [comment]
Not now. But it is very simple to do it. You can modify this function in qa-filtertags-overrides.php as follows

 function qa_db_posts_basic_selectspec($voteuserid=null, $full=false, $user=true)
{
	$globalfiltertagstring = implode("','", explode(",", qa_opt('qa-filtertags-global')));
	$res = qa_db_posts_basic_selectspec_base($voteuserid, $full, $user);
if($this -> template === 'questions' || $this->template === 'activity')
	$res['source'] .= " and ^posts.postid not in(select postid  from ^posttags pt where pt.wordid  in (select wordid from ^words wd where wd.word in ('$globalfiltertagstring'))) ";
	return $res;
}
